volumes:
  pg-data:

services:
  spring:
    image: "bugbee-spring:latest"
    build:
      context: .
      dockerfile: Dockerfiles/spring-Dockerfile
    depends_on:
      - db
      - fastapi
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MAIL_EMAIL=${MAIL_EMAIL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - STORAGE=${STORAGE}
    volumes:
      - ${STORAGE}:/bugbee
    networks:
      - backend

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # Comment this ports for production
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: "bugbee-nginx:latest"
    build:
      context: .
      dockerfile: Dockerfiles/frontend-Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - fastapi
      - spring
      - db

  fastapi:
    image: "bugbee-fastapi:latest"
    build:
      context: .
      dockerfile: Dockerfiles/fastapi-Dockerfile
    volumes:
      - ${STORAGE}:/bugbee
    networks:
      - backend

networks:
  frontend:
  backend: