volumes:
  pg-data:

services:
  app:
    image: "bugbee-backend:latest"
    build:
      context: .
      dockerfile: backend-Dockerfile
    container_name: bugbee
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MAIL_EMAIL=${MAIL_EMAIL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - STORAGE=${STORAGE}
    volumes:
      - ${STORAGE}:/bugbee

  db:
    image: postgres:16
    container_name: postgres-bugbee
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # Comment this ports for production
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  nginx:
    image: "bugbee-nginx:latest"
    container_name: bugbee-nginx
    build:
      context: .
      dockerfile: nginx-Dockerfile
    ports:
      - "80:80"