spring:
  application:
    name: BugBee
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bugbee
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_EMAIL}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: ${SSL_ALIAS}
          keystore:
            location: ${SSL_LOCATION}
            password: ${SSL_PASSWORD}
            type: PKCS12
      pem:
        client:
          truststore:
            certificate: ${SSL_CERTIFICATE_LOCATION}
server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${SSL_LOCATION}
    key-store-password: ${SSL_PASSWORD}
    key-alias: ${SSL_ALIAS}


#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG