spring:
  application:
    name: BugBee
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${POSTGRE_DB}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_EMAIL}
    password: ${SPRING_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG