spring:
  application:
    name: BugBee
  r2dbc:
    url: r2dbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  # comment out below for production
  main:
    lazy-initialization: true

server:
  port: 80

# comment below in production
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
#        web: OFF
#        boot:
#          autoconfigure: OFF