spring:
  application:
    name: BugBee
  r2dbc:
    url: r2dbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# comment/remove below lines if you don't have SSL certificates
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: ${SSL_ALIAS}
          keystore:
            location: ${SSL_LOCATION}
            password: ${SSL_PASSWORD}
            type: PKCS12
      pem:
        client:
          truststore:
            certificate: ${SSL_CERTIFICATE_LOCATION}
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${SSL_LOCATION}
    key-store-password: ${SSL_PASSWORD}
    key-alias: ${SSL_ALIAS}
# comment/remove upto here if you don't have SSL certificates


#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG